export const FETCH_PROFILE_SUMMARY = 'FETCH_PROFILE_SUMMARY';
export const FETCH_PROFILE_IMAGE_URL = 'FETCH_PROFILE_IMAGE_URL';
export const FETCH_ABOUT = 'FETCH_ABOUT';
export const FETCH_TECHNICAL_SKILLS = 'FETCH_TECHNICAL_SKILLS';
export const FETCH_WORK_HISTORY = 'FETCH_WORK_HISTORY';
export const FETCH_EXPERIENCE = 'FETCH_EXPERIENCE';
export const FETCH_FEATURED_PROJECTS = 'FETCH_FEATURED_PROJECTS';
